//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.RH.Sistema.Contratacao.Dominio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aula> Aula { get; set; }
        public virtual DbSet<AvaliacaoComportamental> AvaliacaoComportamental { get; set; }
        public virtual DbSet<CandidatoAula> CandidatoAula { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Fabrica> Fabrica { get; set; }
        public virtual DbSet<Habilidade> Habilidade { get; set; }
        public virtual DbSet<PerfilProfissional> PerfilProfissional { get; set; }
        public virtual DbSet<Unidade> Unidade { get; set; }
        public virtual DbSet<RelatorioHabilidade> RelatorioHabilidade { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Relatorio> Relatorio { get; set; }
        public virtual DbSet<Candidato> Candidato { get; set; }
    }
}
