//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.RH.Sistema.Contratacao.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidato()
        {
            this.CandidatoAula = new HashSet<CandidatoAula>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public bool Publico { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Residencial { get; set; }
        public Nullable<decimal> Celular { get; set; }
        public bool Cv { get; set; }
        public bool Confirmacao { get; set; }
        public bool ProvaTecnica { get; set; }
        public decimal Nota { get; set; }
        public bool Aprovado { get; set; }
        public Nullable<decimal> Rm { get; set; }
        public int IdUnidade { get; set; }
        public int IdFabrica { get; set; }
        public int IdPerfilProfissional { get; set; }
        public int IdCurso { get; set; }
    
        public virtual AvaliacaoComportamental AvaliacaoComportamental { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Fabrica Fabrica { get; set; }
        public virtual PerfilProfissional PerfilProfissional { get; set; }
        public virtual Relatorio Relatorio { get; set; }
        public virtual Unidade Unidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatoAula> CandidatoAula { get; set; }
    }
}
