//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.RH.Sistema.Contratacao.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatorioHabilidade
    {
        public int IdRelatorio { get; set; }
        public int IdHabilidade { get; set; }
        public int IdOrdem { get; set; }
    
        public virtual Habilidade Habilidade { get; set; }
        public virtual Relatorio Relatorio { get; set; }
    }
}
