//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.RH.Sistema.Contratacao.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Relatorio()
        {
            this.RelatorioHabilidades = new HashSet<RelatorioHabilidade>();
        }
    
        public int Id { get; set; }
        public int Faltas { get; set; }
        public int AderenciaComportamental { get; set; }
        public decimal DesempenhoNota { get; set; }
        public string Status { get; set; }
        public int LoginId { get; set; }
    
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatorioHabilidade> RelatorioHabilidades { get; set; }
        public virtual Candidato Candidato { get; set; }
    }
}
